# Generated by Django 4.0.3 on 2022-03-12 00:44

import core.imggenerate
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=200, verbose_name='Название магазина')),
                ('login', models.CharField(max_length=200, unique=True, verbose_name='Логин')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон номер')),
                ('avatar', models.ImageField(null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Почта')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Адресс')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('slogan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=5, verbose_name='Рейтинг')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(max_length=200, null=True)),
                ('nameRus', models.CharField(max_length=200, null=True)),
                ('nameKg', models.CharField(max_length=200, null=True)),
                ('icon', models.ImageField(null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('store', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(max_length=200, null=True)),
                ('nameRus', models.CharField(max_length=200, null=True)),
                ('nameKg', models.CharField(max_length=200, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'Субкатегория',
                'verbose_name_plural': 'Субгатегории',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(max_length=200, null=True)),
                ('nameRus', models.CharField(max_length=200, null=True)),
                ('nameKg', models.CharField(max_length=200, null=True)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
            options={
                'verbose_name': 'Субподкатегория',
                'verbose_name_plural': 'Субподгатегории',
                'ordering': ('-id',),
            },
        ),
    ]
