# Generated by Django 4.0.3 on 2022-12-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
