# Generated by Django 4.0.3 on 2022-03-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='user',
            name='web',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Веб'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ватсап'),
        ),
    ]
