# Generated by Django 4.0.3 on 2022-12-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_store_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularaccount',
            name='bonus',
            field=models.FloatField(default=0, verbose_name='Бонус'),
        ),
        migrations.AddField(
            model_name='regularaccount',
            name='magazin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='store',
            name='cashback',
            field=models.FloatField(default=0, verbose_name='Кэш бэк'),
        ),
    ]
