# Generated by Django 4.0.3 on 2022-12-27 10:26

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_regularaccount_bonus_regularaccount_magazin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sale_type',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Розница'), (2, 'Оптом'), (3, 'Оптом и розница')], default=1, verbose_name='Тип продажи'),
        ),
    ]
