# Generated by Django 4.0.3 on 2023-01-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_store_sale_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('fullName', models.CharField(max_length=100, verbose_name='ФИО')),
                ('pin', models.CharField(max_length=100, verbose_name='PIN')),
                ('isActive', models.BooleanField(default=True, verbose_name='Статус активности')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
        ),
    ]
