# Generated by Django 4.0.3 on 2022-03-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_regularaccount_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
