# Generated by Django 4.0.3 on 2023-01-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_modelagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAgentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.modelagent', verbose_name='Агент')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.regularaccount', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История агент',
                'verbose_name_plural': 'Истории агента',
            },
        ),
    ]
