# Generated by Django 4.0.3 on 2023-01-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_modelagenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecategory',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Приоритет'),
        ),
    ]
