# Generated by Django 4.0.3 on 2022-03-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularaccount',
            name='uid',
            field=models.CharField(max_length=200, unique=True, verbose_name='Код пользователя'),
        ),
    ]
