# Generated by Django 4.0.3 on 2022-03-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_regularaccount_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularaccount',
            options={'verbose_name': 'Обычный пользователь', 'verbose_name_plural': 'Обычные пользователи'},
        ),
        migrations.AlterField(
            model_name='regularaccount',
            name='isoptovik',
            field=models.BooleanField(default=False, verbose_name='Оптовик?'),
        ),
        migrations.AlterField(
            model_name='regularaccount',
            name='optovik_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания оптовика'),
        ),
        migrations.AlterField(
            model_name='regularaccount',
            name='optovik_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы оптовика'),
        ),
    ]
