# Generated by Django 4.0.3 on 2023-01-27 13:39

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_storecategory_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelagenthistory',
            name='type',
            field=django_fsm.FSMIntegerField(blank=True, choices=[(1, 'Оптом'), (2, 'Балл')], default=1, null=True, verbose_name='Тип истории'),
        ),
    ]
