# Generated by Django 4.0.3 on 2022-03-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_regularaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularaccount',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
