# Generated by Django 4.0.3 on 2022-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_alter_regularaccount_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isoptovik',
            field=models.BooleanField(default=False, verbose_name='Оптовик?'),
        ),
    ]
