# Generated by Django 4.0.3 on 2022-03-22 10:27

import core.imggenerate
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_category_isoptovik'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(max_length=200)),
                ('nameRus', models.CharField(max_length=200)),
                ('nameKg', models.CharField(max_length=200)),
                ('icon', models.ImageField(null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Категория магазина',
                'verbose_name_plural': 'Категории магазинов',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='nameEn',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nameKg',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на кыргызком'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nameRus',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.ManyToManyField(blank=True, to='category.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='nameEn',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='nameKg',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на кыргызком'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='nameRus',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='nameEn',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='nameKg',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на кыргызком'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='nameRus',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='store',
            name='storecategory',
            field=models.ManyToManyField(to='category.storecategory', verbose_name='Категория магазина'),
        ),
    ]
