# Generated by Django 4.0.3 on 2022-03-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_storecategory_alter_category_nameen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecategory',
            name='nameEn',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='nameKg',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на кыргызком'),
        ),
        migrations.AlterField(
            model_name='storecategory',
            name='nameRus',
            field=models.CharField(max_length=200, null=True, verbose_name='Название на русском'),
        ),
    ]
