# Generated by Django 4.0.3 on 2022-03-22 12:36

import core.imggenerate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_alter_storecategory_nameen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='avatar',
        ),
        migrations.AddField(
            model_name='store',
            name='priority',
            field=models.FloatField(default=0, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото'),
        ),
    ]
