# Generated by Django 4.0.3 on 2022-09-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_remove_store_avatar_store_priority_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.FloatField(default=0, verbose_name='Приоритет'),
        ),
    ]
