# Generated by Django 4.0.3 on 2022-09-17 12:08

import core.imggenerate
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото банерной рекламы')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Линк')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цвет')),
                ('isoptovik', models.BooleanField(default=False, verbose_name='Оптовик?')),
            ],
            options={
                'verbose_name': 'Банерная реклама',
                'verbose_name_plural': 'Банерные рекламы',
            },
        ),
        migrations.CreateModel(
            name='ModelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField(default=0, verbose_name='ID Магазина')),
                ('totalCost', models.IntegerField(default=0, verbose_name='Общая сумма')),
                ('user', models.CharField(blank=True, max_length=200, null=True, verbose_name='Пользователь')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адресс')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон номер')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарии')),
                ('storeName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название магазина')),
                ('storeLogo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Лого магазина')),
                ('status', django_fsm.FSMIntegerField(choices=[(1, 'Новый'), (2, 'Упаковывается'), (3, 'В пути'), (4, 'Доставлено'), (5, 'Отказано'), (6, 'Отказано')], default=1, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('isoptovik', models.BooleanField(default=False, verbose_name='Оптовик?')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100, verbose_name='Навание категории')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='ServiceSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_title', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория услуги',
                'verbose_name_plural': 'Подкатегории услуг',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('cost', models.FloatField(default=0, verbose_name='Цена услуги')),
                ('costSale', models.FloatField(default=0, verbose_name='Акционная цена услуги')),
                ('issale', models.BooleanField(default=False)),
                ('supplier', models.CharField(blank=True, max_length=500, null=True, verbose_name='Магазин')),
                ('image', models.ImageField(null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('imagelink', models.TextField(blank=True, null=True, verbose_name='Линк фото товара')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон номер')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Инстаграм')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фейсбук')),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ватсап')),
                ('web', models.CharField(blank=True, max_length=200, null=True, verbose_name='Веб')),
                ('likes', models.IntegerField(default=0, verbose_name='Число лайков')),
                ('views', models.IntegerField(default=0, verbose_name='Число просмотров')),
                ('priority', models.FloatField(default=0, verbose_name='Приоритет')),
                ('services_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicecategory')),
                ('services_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicesubcategory')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('cost', models.FloatField(default=0, verbose_name='Цена товара')),
                ('issale', models.BooleanField(default=False, verbose_name='Акционный товар?')),
                ('costSale', models.FloatField(default=0, verbose_name='Акционная цена товара')),
                ('uniqueid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Штрихкод')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('imagelink', models.TextField(blank=True, null=True, verbose_name='Линк фото товара')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон номер')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Инстаграм')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фейсбук')),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ватсап')),
                ('web', models.CharField(blank=True, max_length=200, null=True, verbose_name='Веб')),
                ('likes', models.IntegerField(default=0, verbose_name='Число лайков')),
                ('views', models.IntegerField(default=0, verbose_name='Число просмотров')),
                ('isoptovik', models.BooleanField(default=False, verbose_name='Оптовый товар')),
                ('optovikcost', models.FloatField(default=0, verbose_name='Оптовая цена товара')),
                ('priority', models.FloatField(default=0, verbose_name='Приоритет')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='Категория товара')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subcategory', verbose_name='Сабкатегория товара')),
                ('subsubcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subsubcategory', verbose_name='Субподкатегория товара')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Список товаров',
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item', verbose_name='Товар')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modelorder')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
