# Generated by Django 4.0.3 on 2022-09-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesubcategory',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='services',
            name='services_category',
        ),
        migrations.RemoveField(
            model_name='services',
            name='services_sub_category',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='ServiceSubCategory',
        ),
    ]
