# Generated by Django 4.0.3 on 2022-03-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Список товаров'},
        ),
        migrations.AddField(
            model_name='item',
            name='imagelink',
            field=models.TextField(blank=True, null=True, verbose_name='Линк фото товара'),
        ),
    ]
