# Generated by Django 3.1 on 2022-03-10 19:55

import core.imggenerate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220310_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото'),
        ),
    ]
