# Generated by Django 4.0.3 on 2022-03-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_options_item_imagelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='costsale',
            new_name='costSale',
        ),
        migrations.AddField(
            model_name='item',
            name='issale',
            field=models.BooleanField(default=False),
        ),
    ]
