# Generated by Django 4.0.3 on 2022-03-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_store'),
        ('core', '0003_rename_costsale_item_costsale_item_issale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.store', verbose_name='Магазин'),
        ),
    ]
