# Generated by Django 4.0.3 on 2022-03-14 19:38

import core.imggenerate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото банерной рекламы')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Линк')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('cost', models.FloatField(default=0, verbose_name='Цена услуги')),
                ('costSale', models.FloatField(default=0, verbose_name='Акционная цена услуги')),
                ('issale', models.BooleanField(default=False)),
                ('supplier', models.CharField(blank=True, max_length=500, null=True, verbose_name='Магазин')),
                ('image', models.ImageField(null=True, upload_to=core.imggenerate.all_image_file_path, verbose_name='Фото')),
                ('imagelink', models.TextField(blank=True, null=True, verbose_name='Линк фото товара')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон номер')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Инстаграм')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фейсбук')),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ватсап')),
                ('web', models.CharField(blank=True, max_length=200, null=True, verbose_name='Веб')),
                ('likes', models.IntegerField(default=0, verbose_name='Число лайков')),
                ('views', models.IntegerField(default=0, verbose_name='Число просмотров')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelorder',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
