# Generated by Django 3.1 on 2022-03-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220310_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AddField(
            model_name='item',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Число лайков'),
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Число просмотров'),
        ),
        migrations.AddField(
            model_name='item',
            name='web',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Веб'),
        ),
        migrations.AddField(
            model_name='item',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ватсап'),
        ),
    ]
