# Generated by Django 4.0.3 on 2022-12-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='visibility',
        ),
    ]
