# Generated by Django 4.0.3 on 2022-12-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_regularaccount_bonus_regularaccount_magazin_and_more'),
        ('core', '0005_remove_item_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='bonus',
            field=models.FloatField(default=0, verbose_name='Бонус'),
        ),
        migrations.AddField(
            model_name='modelorder',
            name='pay_status',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='modelorder',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.regularaccount', verbose_name='ID пользователя'),
        ),
        migrations.CreateModel(
            name='BonusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.regularaccount')),
            ],
            options={
                'verbose_name': 'История изменения бонуса',
                'verbose_name_plural': 'История изменения бонусов',
            },
        ),
    ]
