# Generated by Django 4.0.3 on 2022-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_banner_options_item_isoptovik_item_optovikcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='isoptovik',
            field=models.BooleanField(default=False, verbose_name='Оптовик?'),
        ),
    ]
