# Generated by Django 4.0.3 on 2022-12-22 11:34

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modelorder_bonus_modelorder_pay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelorder',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, 'Новый'), (2, 'Упаковывается'), (3, 'В пути'), (4, 'Доставлено'), (5, 'Отказано'), (6, 'Отменен')], default=1, verbose_name='Статус'),
        ),
    ]
