# Generated by Django 4.0.3 on 2022-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_banner_isoptovik'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelorder',
            name='isoptovik',
            field=models.BooleanField(default=False, verbose_name='Оптовик?'),
        ),
    ]
