# Generated by Django 4.0.3 on 2023-01-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bonushistory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, verbose_name='Descriptions')),
                ('title', models.CharField(max_length=100)),
                ('itemId', models.CharField(max_length=100)),
            ],
        ),
    ]
