# Generated by Django 4.0.3 on 2022-03-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_item_issale'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.FloatField(default=0, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='services',
            name='priority',
            field=models.FloatField(default=0, verbose_name='Приоритет'),
        ),
    ]
